name: ecommerce_website
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore:
  cupertino_icons: ^1.0.2
  firebase_storage:
  get: ^4.6.6
  iconly: any
  intl: ^0.19.0
  flutter_screenutil: ^5.9.0
  firebase:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  firebase_core_platform_interface: ^5.0.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/fonts/
    - assets/image/
    - assets/icons/
  fonts:
    - family: GilroyBold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
    - family: GilroySemiBold
      fonts:
        - asset: assets/fonts/Gilroy-SemiBold.ttf
    - family: GilroyMedium
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf
    - family: GilroyRegular
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
  uses-material-design: true
  generate: true
